export const dynamic = "force-static";

export function GET() {
  const body = [
    "# Samen Steeve — auth.md",
    "",
    "Agent registration manifest for samensteeve.com.",
    "This is a public-facing portfolio website. All content is publicly accessible without authentication.",
    "",
    "---",
    "",
    "## Agent Audience",
    "",
    "The target audience for this auth.md is AI agents and automated tools that wish to:",
    "",
    "- Read portfolio projects and case studies",
    "- Browse technical articles and blog posts",
    "- Access the owner's professional bio, skills, and experience",
    "",
    "## Discovery",
    "",
    "1. Fetch `https://samensteeve.com/.well-known/oauth-protected-resource` for resource metadata",
    "2. Fetch `https://samensteeve.com/.well-known/oauth-authorization-server` for authorization server metadata containing the `agent_auth` block",
    "3. The `agent_auth.skill` field points to this file (`https://samensteeve.com/auth.md`)",
    "4. The `agent_auth.register_uri` provides the registration endpoint",
    "",
    "## Registration Methods",
    "",
    "### Anonymous",
    "",
    "No registration required. All content is publicly accessible.",
    "",
    "1. **Discover** — Fetch `https://samensteeve.com/.well-known/oauth-authorization-server` to obtain `agent_auth` metadata",
    "2. **Identify** — Use identity type `anonymous`, credential type `none`",
    "3. **Access** — Request content directly at any public URL on `samensteeve.com` without headers or tokens",
    "4. **Scope** — All requests are scoped to `public:read`",
    "",
    "> Credential type `none` means the agent does not need to present any credential.",
    "> The site has no protected resources; every page and API endpoint is world-readable.",
    "",
    "## Credential Usage",
    "",
    "Since the site is fully public, agents may:",
    "",
    "- Read and index all public pages without credentials",
    "- Access structured data via the WebMCP `navigator.modelContext` API (browser context)",
    "- Request content as Markdown via `Accept: text/markdown` header",
    "- Discover available content via `/.well-known/agent-skills/index.json`",
    "",
    "## Contact",
    "",
    "For inquiries about agent access or commercial use: contact@samensteeve.com",
    "",
    "---",
    "",
    "See https://workos.com/auth-md for the Auth.md specification.",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
    },
  });
}
