import { NextRequest, NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { getT, type Language } from "@/lib/translations";

const CONTENT_DIR = join(process.cwd(), "src/content");

function readMdxFile(filePath: string): string | null {
  try {
    return readFileSync(filePath, "utf-8");
  } catch {
    return null;
  }
}

function langFromSlug(slug: string[]): Language {
  return (slug[0] === "fr" ? "fr" : "en") as Language;
}

function stripPrefix(slug: string[]): string[] {
  return slug.slice(1);
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string[] }> },
) {
  const slug = (await params).slug;
  if (!slug || slug.length === 0) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const lang = langFromSlug(slug);
  const t = getT(lang);
  const rest = stripPrefix(slug);

  // /en or /fr — homepage
  if (rest.length === 0) {
    const lines = [
      `# ${t.nav.work} — Samen Steeve`,
      "",
      `> ${t.hero.status}`,
      `> ${t.hero.location}`,
      "",
      t.hero.bio,
      "",
      "## About me",
      "",
      `**${t.about.q1}**`,
      t.about.a1,
      "",
      `**${t.about.q2}**`,
      t.about.a2,
      "",
      `**${t.about.q3}**`,
      t.about.a3,
      "",
      `**${t.about.q4}**`,
      t.about.a4,
      "",
      "## Sections",
      "",
      `- [Work](${lang === "fr" ? "/fr" : "/en"}/work)`,
      `- [Writing](${lang === "fr" ? "/fr" : "/en"}/writing)`,
      "",
      `---`,
      `_Generated by samensteeve.com · ${new Date().toISOString().split("T")[0]}_`,
    ];
    return new Response(lines.join("\n"), {
      headers: { "Content-Type": "text/markdown; charset=utf-8" },
    });
  }

  const contentType = rest[0];

  // /en/work or /fr/work
  if (contentType === "work") {
    if (rest.length === 1) {
      const workDir = join(CONTENT_DIR, "work");
      const files = readFileSync(workDir, "utf-8")
        .split("\n")
        .filter(Boolean)
        .filter(f => f.endsWith(".mdx"))
        .map(f => f.replace(".mdx", ""));

      const items = files.map(file => {
        const raw = readMdxFile(join(workDir, `${file}.mdx`));
        if (!raw) return null;
        const title = raw.match(/title:\s*"([^"]+)"/)?.[1] || file;
        const desc = raw.match(/description:\s*"([^"]+)"/)?.[1] || "";
        const status = raw.match(/status:\s*"([^"]+)"/)?.[1] || "";
        return { title, desc, status, slug: file };
      }).filter(Boolean);

      const lines = [
        `# Work — Samen Steeve`,
        "",
        items.map(i => `- [${i!.title}](/en/work/${i!.slug})${i!.desc ? ` — ${i!.desc}` : ""}${i!.status ? ` (${i!.status})` : ""}`).join("\n"),
        "",
        `_${items.length} project${items.length > 1 ? "s" : ""}_`,
      ];
      return new Response(lines.join("\n"), {
        headers: { "Content-Type": "text/markdown; charset=utf-8" },
      });
    }

    // /en/work/[slug] — single work page
    const workSlug = rest[1];
    const workFile = join(CONTENT_DIR, "work", `${workSlug}.mdx`);
    const mdx = readMdxFile(workFile);
    if (!mdx) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return new Response(mdx, {
      headers: { "Content-Type": "text/markdown; charset=utf-8" },
    });
  }

  // /en/writing or /fr/writing
  if (contentType === "writing") {
    if (rest.length === 1) {
      const writingDir = join(CONTENT_DIR, "writing", lang);
      if (!existsSync(writingDir)) {
        return NextResponse.json({ error: "Not found" }, { status: 404 });
      }
      const files = readFileSync(writingDir, "utf-8")
        .split("\n")
        .filter(Boolean)
        .filter(f => f.endsWith(".mdx"))
        .map(f => f.replace(".mdx", ""));

      const items = files.map(file => {
        const raw = readMdxFile(join(writingDir, `${file}.mdx`));
        if (!raw) return null;
        const title = raw.match(/title:\s*"([^"]+)"/)?.[1] || file;
        const desc = raw.match(/description:\s*"([^"]+)"/)?.[1] || "";
        const date = raw.match(/date:\s*"([^"]+)"/)?.[1] || "";
        const tags = raw.match(/tags:\s*\[([^\]]+)\]/)?.[1] || "";
        return { title, desc, date, tags, slug: file };
      }).filter(Boolean);

      const lines = [
        `# Writing — Samen Steeve`,
        "",
        items.map(i => {
          const tagStr = i!.tags ? ` [${i!.tags.replace(/"/g, "").replace(/,/g, ", ")}]` : "";
          return `- [${i!.title}](/en/writing/${i!.slug})${i!.date ? ` (${i!.date})` : ""}${tagStr}${i!.desc ? ` — ${i!.desc}` : ""}`;
        }).join("\n"),
        "",
        `_${items.length} article${items.length > 1 ? "s" : ""}_`,
      ];
      return new Response(lines.join("\n"), {
        headers: { "Content-Type": "text/markdown; charset=utf-8" },
      });
    }

    // /en/writing/[slug] — single article
    const writingSlug = rest.slice(1).join("/");
    const writingFile = join(CONTENT_DIR, "writing", lang, `${writingSlug}.mdx`);
    const mdx = readMdxFile(writingFile);
    if (!mdx) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return new Response(mdx, {
      headers: { "Content-Type": "text/markdown; charset=utf-8" },
    });
  }

  return NextResponse.json({ error: "Not found" }, { status: 404 });
}
